[book]
authors = ["Jacob Morgan"]
language = "en"
src = "src"
title = "Oxidize — User Guide"

[build]
build-dir = "site"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/devclef/oxidize"
